/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// FinancialStatements struct for FinancialStatements
type FinancialStatements struct {
	// Symbol of the company.
	Symbol string `json:"symbol,omitempty"`
	// An array of map of key, value pairs containing the data for each period.
	Financials []map[string]interface{} `json:"financials,omitempty"`
}
