/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// Economic struct for Economic
type Economic struct {
	// Date of the reading
	Date string `json:"date,omitempty"`
	// Value
	Value float32 `json:"value,omitempty"`
}
