/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// Sentiment struct for Sentiment
type Sentiment struct {
	// 
	BearishPercent int64 `json:"bearishPercent,omitempty"`
	// 
	BullishPercent int64 `json:"bullishPercent,omitempty"`
}
