/*
Finnhub API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finnhub

import (
	"encoding/json"
)

// InstitutionalOwnership struct for InstitutionalOwnership
type InstitutionalOwnership struct {
	// Symbol.
	Symbol *string `json:"symbol,omitempty"`
	// Cusip.
	Cusip *string `json:"cusip,omitempty"`
	// Array of institutional investors.
	Data *[]InstitutionalOwnershipGroup `json:"data,omitempty"`
}

// NewInstitutionalOwnership instantiates a new InstitutionalOwnership object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstitutionalOwnership() *InstitutionalOwnership {
	this := InstitutionalOwnership{}
	return &this
}

// NewInstitutionalOwnershipWithDefaults instantiates a new InstitutionalOwnership object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstitutionalOwnershipWithDefaults() *InstitutionalOwnership {
	this := InstitutionalOwnership{}
	return &this
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *InstitutionalOwnership) GetSymbol() string {
	if o == nil || o.Symbol == nil {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstitutionalOwnership) GetSymbolOk() (*string, bool) {
	if o == nil || o.Symbol == nil {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *InstitutionalOwnership) HasSymbol() bool {
	if o != nil && o.Symbol != nil {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *InstitutionalOwnership) SetSymbol(v string) {
	o.Symbol = &v
}

// GetCusip returns the Cusip field value if set, zero value otherwise.
func (o *InstitutionalOwnership) GetCusip() string {
	if o == nil || o.Cusip == nil {
		var ret string
		return ret
	}
	return *o.Cusip
}

// GetCusipOk returns a tuple with the Cusip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstitutionalOwnership) GetCusipOk() (*string, bool) {
	if o == nil || o.Cusip == nil {
		return nil, false
	}
	return o.Cusip, true
}

// HasCusip returns a boolean if a field has been set.
func (o *InstitutionalOwnership) HasCusip() bool {
	if o != nil && o.Cusip != nil {
		return true
	}

	return false
}

// SetCusip gets a reference to the given string and assigns it to the Cusip field.
func (o *InstitutionalOwnership) SetCusip(v string) {
	o.Cusip = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *InstitutionalOwnership) GetData() []InstitutionalOwnershipGroup {
	if o == nil || o.Data == nil {
		var ret []InstitutionalOwnershipGroup
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstitutionalOwnership) GetDataOk() (*[]InstitutionalOwnershipGroup, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *InstitutionalOwnership) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []InstitutionalOwnershipGroup and assigns it to the Data field.
func (o *InstitutionalOwnership) SetData(v []InstitutionalOwnershipGroup) {
	o.Data = &v
}

func (o InstitutionalOwnership) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	if o.Cusip != nil {
		toSerialize["cusip"] = o.Cusip
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableInstitutionalOwnership struct {
	value *InstitutionalOwnership
	isSet bool
}

func (v NullableInstitutionalOwnership) Get() *InstitutionalOwnership {
	return v.value
}

func (v *NullableInstitutionalOwnership) Set(val *InstitutionalOwnership) {
	v.value = val
	v.isSet = true
}

func (v NullableInstitutionalOwnership) IsSet() bool {
	return v.isSet
}

func (v *NullableInstitutionalOwnership) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstitutionalOwnership(val *InstitutionalOwnership) *NullableInstitutionalOwnership {
	return &NullableInstitutionalOwnership{value: val, isSet: true}
}

func (v NullableInstitutionalOwnership) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstitutionalOwnership) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


