/*
Finnhub API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finnhub

import (
	"encoding/json"
)

// InFilingSearchBody struct for InFilingSearchBody
type InFilingSearchBody struct {
	// Search query
	Query string `json:"query"`
	// Filing Id to search
	FilingId string `json:"filingId"`
}

// NewInFilingSearchBody instantiates a new InFilingSearchBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInFilingSearchBody(query string, filingId string) *InFilingSearchBody {
	this := InFilingSearchBody{}
	this.Query = query
	this.FilingId = filingId
	return &this
}

// NewInFilingSearchBodyWithDefaults instantiates a new InFilingSearchBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInFilingSearchBodyWithDefaults() *InFilingSearchBody {
	this := InFilingSearchBody{}
	return &this
}

// GetQuery returns the Query field value
func (o *InFilingSearchBody) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *InFilingSearchBody) GetQueryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *InFilingSearchBody) SetQuery(v string) {
	o.Query = v
}

// GetFilingId returns the FilingId field value
func (o *InFilingSearchBody) GetFilingId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilingId
}

// GetFilingIdOk returns a tuple with the FilingId field value
// and a boolean to check if the value has been set.
func (o *InFilingSearchBody) GetFilingIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FilingId, true
}

// SetFilingId sets field value
func (o *InFilingSearchBody) SetFilingId(v string) {
	o.FilingId = v
}

func (o InFilingSearchBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["query"] = o.Query
	}
	if true {
		toSerialize["filingId"] = o.FilingId
	}
	return json.Marshal(toSerialize)
}

type NullableInFilingSearchBody struct {
	value *InFilingSearchBody
	isSet bool
}

func (v NullableInFilingSearchBody) Get() *InFilingSearchBody {
	return v.value
}

func (v *NullableInFilingSearchBody) Set(val *InFilingSearchBody) {
	v.value = val
	v.isSet = true
}

func (v NullableInFilingSearchBody) IsSet() bool {
	return v.isSet
}

func (v *NullableInFilingSearchBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInFilingSearchBody(val *InFilingSearchBody) *NullableInFilingSearchBody {
	return &NullableInFilingSearchBody{value: val, isSet: true}
}

func (v NullableInFilingSearchBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInFilingSearchBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


