/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
import (
	"time"
)
// Development struct for Development
type Development struct {
	// Company symbol.
	Symbol string `json:"symbol,omitempty"`
	// Published time in <code>YYYY-MM-DD HH:MM:SS</code> format.
	Datetime time.Time `json:"datetime,omitempty"`
	// Development headline.
	Headline string `json:"headline,omitempty"`
	// Development description.
	Description string `json:"description,omitempty"`
}
