/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// EtFsHoldings struct for EtFsHoldings
type EtFsHoldings struct {
	// ETF symbol.
	Symbol string `json:"symbol,omitempty"`
	// Array of holdings.
	Holdings []map[string]interface{} `json:"holdings,omitempty"`
}
