/*
Finnhub API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finnhub

import (
	"encoding/json"
)

// InstitutionalPortfolio struct for InstitutionalPortfolio
type InstitutionalPortfolio struct {
	// Investor's name.
	Name *string `json:"name,omitempty"`
	// CIK.
	Cik *string `json:"cik,omitempty"`
	// Array of positions.
	Data *[]InstitutionalPortfolioGroup `json:"data,omitempty"`
}

// NewInstitutionalPortfolio instantiates a new InstitutionalPortfolio object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstitutionalPortfolio() *InstitutionalPortfolio {
	this := InstitutionalPortfolio{}
	return &this
}

// NewInstitutionalPortfolioWithDefaults instantiates a new InstitutionalPortfolio object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstitutionalPortfolioWithDefaults() *InstitutionalPortfolio {
	this := InstitutionalPortfolio{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InstitutionalPortfolio) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstitutionalPortfolio) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InstitutionalPortfolio) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InstitutionalPortfolio) SetName(v string) {
	o.Name = &v
}

// GetCik returns the Cik field value if set, zero value otherwise.
func (o *InstitutionalPortfolio) GetCik() string {
	if o == nil || o.Cik == nil {
		var ret string
		return ret
	}
	return *o.Cik
}

// GetCikOk returns a tuple with the Cik field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstitutionalPortfolio) GetCikOk() (*string, bool) {
	if o == nil || o.Cik == nil {
		return nil, false
	}
	return o.Cik, true
}

// HasCik returns a boolean if a field has been set.
func (o *InstitutionalPortfolio) HasCik() bool {
	if o != nil && o.Cik != nil {
		return true
	}

	return false
}

// SetCik gets a reference to the given string and assigns it to the Cik field.
func (o *InstitutionalPortfolio) SetCik(v string) {
	o.Cik = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *InstitutionalPortfolio) GetData() []InstitutionalPortfolioGroup {
	if o == nil || o.Data == nil {
		var ret []InstitutionalPortfolioGroup
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstitutionalPortfolio) GetDataOk() (*[]InstitutionalPortfolioGroup, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *InstitutionalPortfolio) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []InstitutionalPortfolioGroup and assigns it to the Data field.
func (o *InstitutionalPortfolio) SetData(v []InstitutionalPortfolioGroup) {
	o.Data = &v
}

func (o InstitutionalPortfolio) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Cik != nil {
		toSerialize["cik"] = o.Cik
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableInstitutionalPortfolio struct {
	value *InstitutionalPortfolio
	isSet bool
}

func (v NullableInstitutionalPortfolio) Get() *InstitutionalPortfolio {
	return v.value
}

func (v *NullableInstitutionalPortfolio) Set(val *InstitutionalPortfolio) {
	v.value = val
	v.isSet = true
}

func (v NullableInstitutionalPortfolio) IsSet() bool {
	return v.isSet
}

func (v *NullableInstitutionalPortfolio) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstitutionalPortfolio(val *InstitutionalPortfolio) *NullableInstitutionalPortfolio {
	return &NullableInstitutionalPortfolio{value: val, isSet: true}
}

func (v NullableInstitutionalPortfolio) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstitutionalPortfolio) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


