/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finnhub

import (
	"encoding/json"
)

// RevenueBreakdown struct for RevenueBreakdown
type RevenueBreakdown struct {
	// Symbol
	Symbol *string `json:"symbol,omitempty"`
	// CIK
	Cik *string `json:"cik,omitempty"`
	// Array of revenue breakdown over multiple periods.
	Data *[]map[string]interface{} `json:"data,omitempty"`
}

// NewRevenueBreakdown instantiates a new RevenueBreakdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevenueBreakdown() *RevenueBreakdown {
	this := RevenueBreakdown{}
	return &this
}

// NewRevenueBreakdownWithDefaults instantiates a new RevenueBreakdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevenueBreakdownWithDefaults() *RevenueBreakdown {
	this := RevenueBreakdown{}
	return &this
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *RevenueBreakdown) GetSymbol() string {
	if o == nil || o.Symbol == nil {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevenueBreakdown) GetSymbolOk() (*string, bool) {
	if o == nil || o.Symbol == nil {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *RevenueBreakdown) HasSymbol() bool {
	if o != nil && o.Symbol != nil {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *RevenueBreakdown) SetSymbol(v string) {
	o.Symbol = &v
}

// GetCik returns the Cik field value if set, zero value otherwise.
func (o *RevenueBreakdown) GetCik() string {
	if o == nil || o.Cik == nil {
		var ret string
		return ret
	}
	return *o.Cik
}

// GetCikOk returns a tuple with the Cik field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevenueBreakdown) GetCikOk() (*string, bool) {
	if o == nil || o.Cik == nil {
		return nil, false
	}
	return o.Cik, true
}

// HasCik returns a boolean if a field has been set.
func (o *RevenueBreakdown) HasCik() bool {
	if o != nil && o.Cik != nil {
		return true
	}

	return false
}

// SetCik gets a reference to the given string and assigns it to the Cik field.
func (o *RevenueBreakdown) SetCik(v string) {
	o.Cik = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RevenueBreakdown) GetData() []map[string]interface{} {
	if o == nil || o.Data == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevenueBreakdown) GetDataOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RevenueBreakdown) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []map[string]interface{} and assigns it to the Data field.
func (o *RevenueBreakdown) SetData(v []map[string]interface{}) {
	o.Data = &v
}

func (o RevenueBreakdown) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	if o.Cik != nil {
		toSerialize["cik"] = o.Cik
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableRevenueBreakdown struct {
	value *RevenueBreakdown
	isSet bool
}

func (v NullableRevenueBreakdown) Get() *RevenueBreakdown {
	return v.value
}

func (v *NullableRevenueBreakdown) Set(val *RevenueBreakdown) {
	v.value = val
	v.isSet = true
}

func (v NullableRevenueBreakdown) IsSet() bool {
	return v.isSet
}

func (v *NullableRevenueBreakdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevenueBreakdown(val *RevenueBreakdown) *NullableRevenueBreakdown {
	return &NullableRevenueBreakdown{value: val, isSet: true}
}

func (v NullableRevenueBreakdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevenueBreakdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


