/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// IpoCalendar struct for IpoCalendar
type IpoCalendar struct {
	// Array of IPO events.
	IpoCalendar []map[string]interface{} `json:"ipoCalendar,omitempty"`
}
