/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// CompanyNewsStatistics struct for CompanyNewsStatistics
type CompanyNewsStatistics struct {
	// 
	ArticlesInLastWeek int64 `json:"articlesInLastWeek,omitempty"`
	// 
	Buzz float32 `json:"buzz,omitempty"`
	// 
	WeeklyAverage float32 `json:"weeklyAverage,omitempty"`
}
