/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// EarningRelease struct for EarningRelease
type EarningRelease struct {
	// Symbol.
	Symbol string `json:"symbol,omitempty"`
	// Date.
	Date string `json:"date,omitempty"`
	// Indicates whether the earnings is announced before market open(<code>bmo</code>), after market close(<code>amc</code>), or during market hour(<code>dmh</code>).
	Hour string `json:"hour,omitempty"`
	// Earnings year.
	Year int64 `json:"year,omitempty"`
	// Earnings quarter.
	Quarter int64 `json:"quarter,omitempty"`
	// EPS estimate.
	EpsEstimate float32 `json:"epsEstimate,omitempty"`
	// EPS actual.
	EpsActual float32 `json:"epsActual,omitempty"`
	// Revenue estimate.
	RevenueEstimate int64 `json:"revenueEstimate,omitempty"`
	// Revenue actual.
	RevenueActual int64 `json:"revenueActual,omitempty"`
}
