/*
Finnhub API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finnhub

import (
	"encoding/json"
)

// ETFsHoldings struct for ETFsHoldings
type ETFsHoldings struct {
	// ETF symbol.
	Symbol *string `json:"symbol,omitempty"`
	// Holdings update date.
	AtDate *string `json:"atDate,omitempty"`
	// Number of holdings.
	NumberOfHoldings *int64 `json:"numberOfHoldings,omitempty"`
	// Array of holdings.
	Holdings *[]ETFHoldingsData `json:"holdings,omitempty"`
}

// NewETFsHoldings instantiates a new ETFsHoldings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewETFsHoldings() *ETFsHoldings {
	this := ETFsHoldings{}
	return &this
}

// NewETFsHoldingsWithDefaults instantiates a new ETFsHoldings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewETFsHoldingsWithDefaults() *ETFsHoldings {
	this := ETFsHoldings{}
	return &this
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *ETFsHoldings) GetSymbol() string {
	if o == nil || o.Symbol == nil {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ETFsHoldings) GetSymbolOk() (*string, bool) {
	if o == nil || o.Symbol == nil {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *ETFsHoldings) HasSymbol() bool {
	if o != nil && o.Symbol != nil {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *ETFsHoldings) SetSymbol(v string) {
	o.Symbol = &v
}

// GetAtDate returns the AtDate field value if set, zero value otherwise.
func (o *ETFsHoldings) GetAtDate() string {
	if o == nil || o.AtDate == nil {
		var ret string
		return ret
	}
	return *o.AtDate
}

// GetAtDateOk returns a tuple with the AtDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ETFsHoldings) GetAtDateOk() (*string, bool) {
	if o == nil || o.AtDate == nil {
		return nil, false
	}
	return o.AtDate, true
}

// HasAtDate returns a boolean if a field has been set.
func (o *ETFsHoldings) HasAtDate() bool {
	if o != nil && o.AtDate != nil {
		return true
	}

	return false
}

// SetAtDate gets a reference to the given string and assigns it to the AtDate field.
func (o *ETFsHoldings) SetAtDate(v string) {
	o.AtDate = &v
}

// GetNumberOfHoldings returns the NumberOfHoldings field value if set, zero value otherwise.
func (o *ETFsHoldings) GetNumberOfHoldings() int64 {
	if o == nil || o.NumberOfHoldings == nil {
		var ret int64
		return ret
	}
	return *o.NumberOfHoldings
}

// GetNumberOfHoldingsOk returns a tuple with the NumberOfHoldings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ETFsHoldings) GetNumberOfHoldingsOk() (*int64, bool) {
	if o == nil || o.NumberOfHoldings == nil {
		return nil, false
	}
	return o.NumberOfHoldings, true
}

// HasNumberOfHoldings returns a boolean if a field has been set.
func (o *ETFsHoldings) HasNumberOfHoldings() bool {
	if o != nil && o.NumberOfHoldings != nil {
		return true
	}

	return false
}

// SetNumberOfHoldings gets a reference to the given int64 and assigns it to the NumberOfHoldings field.
func (o *ETFsHoldings) SetNumberOfHoldings(v int64) {
	o.NumberOfHoldings = &v
}

// GetHoldings returns the Holdings field value if set, zero value otherwise.
func (o *ETFsHoldings) GetHoldings() []ETFHoldingsData {
	if o == nil || o.Holdings == nil {
		var ret []ETFHoldingsData
		return ret
	}
	return *o.Holdings
}

// GetHoldingsOk returns a tuple with the Holdings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ETFsHoldings) GetHoldingsOk() (*[]ETFHoldingsData, bool) {
	if o == nil || o.Holdings == nil {
		return nil, false
	}
	return o.Holdings, true
}

// HasHoldings returns a boolean if a field has been set.
func (o *ETFsHoldings) HasHoldings() bool {
	if o != nil && o.Holdings != nil {
		return true
	}

	return false
}

// SetHoldings gets a reference to the given []ETFHoldingsData and assigns it to the Holdings field.
func (o *ETFsHoldings) SetHoldings(v []ETFHoldingsData) {
	o.Holdings = &v
}

func (o ETFsHoldings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	if o.AtDate != nil {
		toSerialize["atDate"] = o.AtDate
	}
	if o.NumberOfHoldings != nil {
		toSerialize["numberOfHoldings"] = o.NumberOfHoldings
	}
	if o.Holdings != nil {
		toSerialize["holdings"] = o.Holdings
	}
	return json.Marshal(toSerialize)
}

type NullableETFsHoldings struct {
	value *ETFsHoldings
	isSet bool
}

func (v NullableETFsHoldings) Get() *ETFsHoldings {
	return v.value
}

func (v *NullableETFsHoldings) Set(val *ETFsHoldings) {
	v.value = val
	v.isSet = true
}

func (v NullableETFsHoldings) IsSet() bool {
	return v.isSet
}

func (v *NullableETFsHoldings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableETFsHoldings(val *ETFsHoldings) *NullableETFsHoldings {
	return &NullableETFsHoldings{value: val, isSet: true}
}

func (v NullableETFsHoldings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableETFsHoldings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


