/*
Finnhub API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finnhub

import (
	"encoding/json"
)

// PriceMetrics struct for PriceMetrics
type PriceMetrics struct {
	// Symbol of the company.
	Symbol *string `json:"symbol,omitempty"`
	Data *map[string]interface{} `json:"data,omitempty"`
}

// NewPriceMetrics instantiates a new PriceMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPriceMetrics() *PriceMetrics {
	this := PriceMetrics{}
	return &this
}

// NewPriceMetricsWithDefaults instantiates a new PriceMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPriceMetricsWithDefaults() *PriceMetrics {
	this := PriceMetrics{}
	return &this
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *PriceMetrics) GetSymbol() string {
	if o == nil || o.Symbol == nil {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceMetrics) GetSymbolOk() (*string, bool) {
	if o == nil || o.Symbol == nil {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *PriceMetrics) HasSymbol() bool {
	if o != nil && o.Symbol != nil {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *PriceMetrics) SetSymbol(v string) {
	o.Symbol = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PriceMetrics) GetData() map[string]interface{} {
	if o == nil || o.Data == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PriceMetrics) GetDataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PriceMetrics) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *PriceMetrics) SetData(v map[string]interface{}) {
	o.Data = &v
}

func (o PriceMetrics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullablePriceMetrics struct {
	value *PriceMetrics
	isSet bool
}

func (v NullablePriceMetrics) Get() *PriceMetrics {
	return v.value
}

func (v *NullablePriceMetrics) Set(val *PriceMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullablePriceMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullablePriceMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePriceMetrics(val *PriceMetrics) *NullablePriceMetrics {
	return &NullablePriceMetrics{value: val, isSet: true}
}

func (v NullablePriceMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePriceMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


