/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// StockExchange struct for StockExchange
type StockExchange struct {
	// Exchange name.
	Name string `json:"name,omitempty"`
	// Exchange code.
	Code string `json:"code,omitempty"`
	// Currency.
	Currency string `json:"currency,omitempty"`
}
