/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finnhub

import (
	"encoding/json"
)

// InsiderTransactions struct for InsiderTransactions
type InsiderTransactions struct {
	// Symbol of the company.
	Symbol *string `json:"symbol,omitempty"`
	// Array of insider transactions.
	Data *[]Transactions `json:"data,omitempty"`
}

// NewInsiderTransactions instantiates a new InsiderTransactions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInsiderTransactions() *InsiderTransactions {
	this := InsiderTransactions{}
	return &this
}

// NewInsiderTransactionsWithDefaults instantiates a new InsiderTransactions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInsiderTransactionsWithDefaults() *InsiderTransactions {
	this := InsiderTransactions{}
	return &this
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *InsiderTransactions) GetSymbol() string {
	if o == nil || o.Symbol == nil {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsiderTransactions) GetSymbolOk() (*string, bool) {
	if o == nil || o.Symbol == nil {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *InsiderTransactions) HasSymbol() bool {
	if o != nil && o.Symbol != nil {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *InsiderTransactions) SetSymbol(v string) {
	o.Symbol = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *InsiderTransactions) GetData() []Transactions {
	if o == nil || o.Data == nil {
		var ret []Transactions
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InsiderTransactions) GetDataOk() (*[]Transactions, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *InsiderTransactions) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []Transactions and assigns it to the Data field.
func (o *InsiderTransactions) SetData(v []Transactions) {
	o.Data = &v
}

func (o InsiderTransactions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableInsiderTransactions struct {
	value *InsiderTransactions
	isSet bool
}

func (v NullableInsiderTransactions) Get() *InsiderTransactions {
	return v.value
}

func (v *NullableInsiderTransactions) Set(val *InsiderTransactions) {
	v.value = val
	v.isSet = true
}

func (v NullableInsiderTransactions) IsSet() bool {
	return v.isSet
}

func (v *NullableInsiderTransactions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsiderTransactions(val *InsiderTransactions) *NullableInsiderTransactions {
	return &NullableInsiderTransactions{value: val, isSet: true}
}

func (v NullableInsiderTransactions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsiderTransactions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


