/*
Finnhub API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finnhub

import (
	"encoding/json"
)

// MutualFundEetPai struct for MutualFundEetPai
type MutualFundEetPai struct {
	// ISIN.
	Isin *string `json:"isin,omitempty"`
	Data *map[string]interface{} `json:"data,omitempty"`
}

// NewMutualFundEetPai instantiates a new MutualFundEetPai object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMutualFundEetPai() *MutualFundEetPai {
	this := MutualFundEetPai{}
	return &this
}

// NewMutualFundEetPaiWithDefaults instantiates a new MutualFundEetPai object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMutualFundEetPaiWithDefaults() *MutualFundEetPai {
	this := MutualFundEetPai{}
	return &this
}

// GetIsin returns the Isin field value if set, zero value otherwise.
func (o *MutualFundEetPai) GetIsin() string {
	if o == nil || o.Isin == nil {
		var ret string
		return ret
	}
	return *o.Isin
}

// GetIsinOk returns a tuple with the Isin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutualFundEetPai) GetIsinOk() (*string, bool) {
	if o == nil || o.Isin == nil {
		return nil, false
	}
	return o.Isin, true
}

// HasIsin returns a boolean if a field has been set.
func (o *MutualFundEetPai) HasIsin() bool {
	if o != nil && o.Isin != nil {
		return true
	}

	return false
}

// SetIsin gets a reference to the given string and assigns it to the Isin field.
func (o *MutualFundEetPai) SetIsin(v string) {
	o.Isin = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *MutualFundEetPai) GetData() map[string]interface{} {
	if o == nil || o.Data == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MutualFundEetPai) GetDataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *MutualFundEetPai) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *MutualFundEetPai) SetData(v map[string]interface{}) {
	o.Data = &v
}

func (o MutualFundEetPai) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Isin != nil {
		toSerialize["isin"] = o.Isin
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableMutualFundEetPai struct {
	value *MutualFundEetPai
	isSet bool
}

func (v NullableMutualFundEetPai) Get() *MutualFundEetPai {
	return v.value
}

func (v *NullableMutualFundEetPai) Set(val *MutualFundEetPai) {
	v.value = val
	v.isSet = true
}

func (v NullableMutualFundEetPai) IsSet() bool {
	return v.isSet
}

func (v *NullableMutualFundEetPai) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMutualFundEetPai(val *MutualFundEetPai) *NullableMutualFundEetPai {
	return &NullableMutualFundEetPai{value: val, isSet: true}
}

func (v NullableMutualFundEetPai) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMutualFundEetPai) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


