/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// EconomicCode struct for EconomicCode
type EconomicCode struct {
	// Finnhub economic code used to get historical data
	Code string `json:"code,omitempty"`
	// Country
	Country string `json:"country,omitempty"`
	// Indicator name
	Name string `json:"name,omitempty"`
	// Unit
	Unit string `json:"unit,omitempty"`
}
