/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// TickData struct for TickData
type TickData struct {
	// Symbol.
	S string `json:"s,omitempty"`
	// Number of ticks skipped.
	Skip int64 `json:"skip,omitempty"`
	// Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned.
	Count int64 `json:"count,omitempty"`
	// Total number of ticks for that date.
	Total int64 `json:"total,omitempty"`
	// List of volume data.
	V []float32 `json:"v,omitempty"`
	// List of price data.
	P []float32 `json:"p,omitempty"`
	// List of timestamp in UNIX ms.
	T []int64 `json:"t,omitempty"`
	// List of venues/exchanges.
	X []string `json:"x,omitempty"`
}
