/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// SupportResistance struct for SupportResistance
type SupportResistance struct {
	// Array of support and resistance levels.
	Levels []float32 `json:"levels,omitempty"`
}
