/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package finnhub

import (
	"encoding/json"
)

// Estimate struct for Estimate
type Estimate struct {
	// Average revenue estimates including Finnhub's proprietary estimates.
	RevenueAvg *int64 `json:"revenueAvg,omitempty"`
	// Highest estimate.
	RevenueHigh *int64 `json:"revenueHigh,omitempty"`
	// Lowest estimate.
	RevenueLow *int64 `json:"revenueLow,omitempty"`
	// Number of Analysts.
	NumberAnalysts *int64 `json:"numberAnalysts,omitempty"`
	// Period.
	Period *string `json:"period,omitempty"`
}

// NewEstimate instantiates a new Estimate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEstimate() *Estimate {
	this := Estimate{}
	return &this
}

// NewEstimateWithDefaults instantiates a new Estimate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEstimateWithDefaults() *Estimate {
	this := Estimate{}
	return &this
}

// GetRevenueAvg returns the RevenueAvg field value if set, zero value otherwise.
func (o *Estimate) GetRevenueAvg() int64 {
	if o == nil || o.RevenueAvg == nil {
		var ret int64
		return ret
	}
	return *o.RevenueAvg
}

// GetRevenueAvgOk returns a tuple with the RevenueAvg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Estimate) GetRevenueAvgOk() (*int64, bool) {
	if o == nil || o.RevenueAvg == nil {
		return nil, false
	}
	return o.RevenueAvg, true
}

// HasRevenueAvg returns a boolean if a field has been set.
func (o *Estimate) HasRevenueAvg() bool {
	if o != nil && o.RevenueAvg != nil {
		return true
	}

	return false
}

// SetRevenueAvg gets a reference to the given int64 and assigns it to the RevenueAvg field.
func (o *Estimate) SetRevenueAvg(v int64) {
	o.RevenueAvg = &v
}

// GetRevenueHigh returns the RevenueHigh field value if set, zero value otherwise.
func (o *Estimate) GetRevenueHigh() int64 {
	if o == nil || o.RevenueHigh == nil {
		var ret int64
		return ret
	}
	return *o.RevenueHigh
}

// GetRevenueHighOk returns a tuple with the RevenueHigh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Estimate) GetRevenueHighOk() (*int64, bool) {
	if o == nil || o.RevenueHigh == nil {
		return nil, false
	}
	return o.RevenueHigh, true
}

// HasRevenueHigh returns a boolean if a field has been set.
func (o *Estimate) HasRevenueHigh() bool {
	if o != nil && o.RevenueHigh != nil {
		return true
	}

	return false
}

// SetRevenueHigh gets a reference to the given int64 and assigns it to the RevenueHigh field.
func (o *Estimate) SetRevenueHigh(v int64) {
	o.RevenueHigh = &v
}

// GetRevenueLow returns the RevenueLow field value if set, zero value otherwise.
func (o *Estimate) GetRevenueLow() int64 {
	if o == nil || o.RevenueLow == nil {
		var ret int64
		return ret
	}
	return *o.RevenueLow
}

// GetRevenueLowOk returns a tuple with the RevenueLow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Estimate) GetRevenueLowOk() (*int64, bool) {
	if o == nil || o.RevenueLow == nil {
		return nil, false
	}
	return o.RevenueLow, true
}

// HasRevenueLow returns a boolean if a field has been set.
func (o *Estimate) HasRevenueLow() bool {
	if o != nil && o.RevenueLow != nil {
		return true
	}

	return false
}

// SetRevenueLow gets a reference to the given int64 and assigns it to the RevenueLow field.
func (o *Estimate) SetRevenueLow(v int64) {
	o.RevenueLow = &v
}

// GetNumberAnalysts returns the NumberAnalysts field value if set, zero value otherwise.
func (o *Estimate) GetNumberAnalysts() int64 {
	if o == nil || o.NumberAnalysts == nil {
		var ret int64
		return ret
	}
	return *o.NumberAnalysts
}

// GetNumberAnalystsOk returns a tuple with the NumberAnalysts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Estimate) GetNumberAnalystsOk() (*int64, bool) {
	if o == nil || o.NumberAnalysts == nil {
		return nil, false
	}
	return o.NumberAnalysts, true
}

// HasNumberAnalysts returns a boolean if a field has been set.
func (o *Estimate) HasNumberAnalysts() bool {
	if o != nil && o.NumberAnalysts != nil {
		return true
	}

	return false
}

// SetNumberAnalysts gets a reference to the given int64 and assigns it to the NumberAnalysts field.
func (o *Estimate) SetNumberAnalysts(v int64) {
	o.NumberAnalysts = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *Estimate) GetPeriod() string {
	if o == nil || o.Period == nil {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Estimate) GetPeriodOk() (*string, bool) {
	if o == nil || o.Period == nil {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *Estimate) HasPeriod() bool {
	if o != nil && o.Period != nil {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *Estimate) SetPeriod(v string) {
	o.Period = &v
}

func (o Estimate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RevenueAvg != nil {
		toSerialize["revenueAvg"] = o.RevenueAvg
	}
	if o.RevenueHigh != nil {
		toSerialize["revenueHigh"] = o.RevenueHigh
	}
	if o.RevenueLow != nil {
		toSerialize["revenueLow"] = o.RevenueLow
	}
	if o.NumberAnalysts != nil {
		toSerialize["numberAnalysts"] = o.NumberAnalysts
	}
	if o.Period != nil {
		toSerialize["period"] = o.Period
	}
	return json.Marshal(toSerialize)
}

type NullableEstimate struct {
	value *Estimate
	isSet bool
}

func (v NullableEstimate) Get() *Estimate {
	return v.value
}

func (v *NullableEstimate) Set(val *Estimate) {
	v.value = val
	v.isSet = true
}

func (v NullableEstimate) IsSet() bool {
	return v.isSet
}

func (v *NullableEstimate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstimate(val *Estimate) *NullableEstimate {
	return &NullableEstimate{value: val, isSet: true}
}

func (v NullableEstimate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstimate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


