/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// EtFsProfile struct for EtFsProfile
type EtFsProfile struct {
	// Use symbol returned in <code>/forex/symbol</code> endpoint for this field.
	Symbol string `json:"symbol,omitempty"`
	Profile map[string]interface{} `json:"profile,omitempty"`
}
