/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// Investor struct for Investor
type Investor struct {
	// Investor's name.
	Name string `json:"name,omitempty"`
	// Number of shares held by the investor.
	Share int64 `json:"share,omitempty"`
	// Number of share changed (net buy or sell) from the last period.
	Change int64 `json:"change,omitempty"`
	// Filing date.
	FilingDate string `json:"filingDate,omitempty"`
}
