/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
import (
	"time"
)
// MergerCountry struct for MergerCountry
type MergerCountry struct {
	// Announcement date of the deal.
	AnnouncementDate time.Time `json:"announcementDate,omitempty"`
	// Deal size in millions of USD.
	DealSize float32 `json:"dealSize,omitempty"`
	// Deal status.
	Status string `json:"status,omitempty"`
	// Target company name.
	TargetName string `json:"targetName,omitempty"`
	// Target company country.
	TargetNation string `json:"targetNation,omitempty"`
	// Acquirer name.
	AcquirerName string `json:"acquirerName,omitempty"`
	// Acquirer nation.
	AcquirerNation string `json:"acquirerNation,omitempty"`
	// Deal form.
	Form string `json:"form,omitempty"`
	// Target company industry.
	TargetIndustry string `json:"targetIndustry,omitempty"`
	// Deal form.
	AcquirerIndustry string `json:"acquirerIndustry,omitempty"`
	// Target company business summary.
	TargetDescription string `json:"targetDescription,omitempty"`
	// Acquirer business summary.
	AcquirerDescription string `json:"acquirerDescription,omitempty"`
	// Target company region.
	TargetRegion string `json:"targetRegion,omitempty"`
	// Acquirer company region.
	AcquirerRegion string `json:"acquirerRegion,omitempty"`
	// Target company public status.
	TargetPublicStatus string `json:"targetPublicStatus,omitempty"`
	// Acquirer company public status.
	AcquirerPublicStatus string `json:"acquirerPublicStatus,omitempty"`
	// Deal attitude.
	DealAttitude string `json:"dealAttitude,omitempty"`
	// Net Income Multiple.
	NetincomeMultiple float32 `json:"netincomeMultiple,omitempty"`
	// Percent acquired.
	PercentAcquired float32 `json:"percentAcquired,omitempty"`
}
