/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// EconomicCalendar struct for EconomicCalendar
type EconomicCalendar struct {
	Array map[string]interface{} `json:"Array,omitempty"`
}
