/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// Indicator struct for Indicator
type Indicator struct {
	// Number of buy signals
	Buy int64 `json:"buy,omitempty"`
	// Number of neutral signals
	Neutral int64 `json:"neutral,omitempty"`
	// Number of sell signals
	Sell int64 `json:"sell,omitempty"`
}
