/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package finnhub
// FinancialsAsReported struct for FinancialsAsReported
type FinancialsAsReported struct {
	// Symbol
	Symbol string `json:"symbol,omitempty"`
	// CIK
	Cik string `json:"cik,omitempty"`
	// Array of filings.
	Data []map[string]interface{} `json:"data,omitempty"`
}
